theme: jekyll-theme-midnight
title: Zerkaid's Blog of Things
description: Writeups for CTF's and Labs

lsi: false
safe: true
source: zerkaid
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge